### ISSUE TITLE
refcount design flaw

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#120]
```
It seems to be possible to read object field and have object it points to 
deleted before it is used/ref_inc'ed by reader. Need atomic refcnt inc on each 
read - and field read retry if cnt became zero before we inc'ed it.

In fact it means global refcnt redesign.

Need regression tests for it then.

```

Original issue reported on code.google.com by `dmitry.zavalishin@gmail.com` on 30 Aug 2011 at 9:42

**Comment by dzavalishin** [comment]
store requests for ref_dec on a queue, execute them after snapshot (or just global thread pause request like in snapshot), switching requests to a new queue before that. size of q? use persistent mem for q?

`
switch to new q
snap or pause-run
do ref_dec for old q
`

**Comment by dzavalishin** [comment]
// TODO ERROR atomic_add returns not what we assume!
    int pos = atomic_add( (int *)&refdec_put_ptr, 1 );

**Comment by dzavalishin** [comment]
Attempt to turn on VM_DEFERRED_REFDEC

```
unimplemented vm_mutex_lock used
[31mvm.sync/phantom_check_threads_pass_bytecode_instr_boundary: unimpl![0m
Panic: refdec.c:177, deferred_refdec_thread: assertion 'os->_ah.refCount > 0' failed

```
