### ISSUE TITLE
PS2 mouse reset required

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#133]
```
Sometimes after computer reset PS2 mouse is broken. Suppose some reset needed 
in driver.

```

Original issue reported on code.google.com by `dmitry.zavalishin@gmail.com` on 20 Sep 2011 at 7:54

**Comment by dzavalishin** [comment]
In progress. Mouse reset needs us to read mouse output after each byte sent.
