### ISSUE TITLE
TCP - no timeout

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#138]
```
tcp read does not time out

```

Original issue reported on code.google.com by `dmitry.zavalishin@gmail.com` on 22 Sep 2011 at 12:12

**Comment by dzavalishin** [comment]
Need details

**Comment by dzavalishin** [comment]
Need test that attempts to connect nonexistent host and fails with timeout?

**Comment by my2coins** [comment]
Sounds reasonable

**Comment by dzavalishin** [comment]
Nope. Connect times out. Seems that just read() does not.

**Comment by dzavalishin** [comment]
Read time outs. Can't reproduce.
