### ISSUE TITLE
reschedule on releasing sema in interrupt?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#140]
```
_hal_wait_for_interrupt takes 10% of CPU - seems to be scheduler problem - must 
be 0 when we have non-sleeping thread

```

Original issue reported on code.google.com by `dmitry.zavalishin@gmail.com` on 23 Sep 2011 at 11:05

**Comment by dzavalishin** [comment]
Actually phantom_scheduler_request_reschedule() is called in each thread_unblock()
