### ISSUE TITLE
queueRaisePrio panic

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#160]
```
Panic: disk_q.c:219, queueRaisePrio: assertion '!queue_empty(&(q->requests))' 
failed


```

Original issue reported on code.google.com by `dmitry.zavalishin@gmail.com` on 8 Nov 2011 at 3:12

**Comment by dzavalishin** [comment]
Actually doesn't happen. Postpone for now.

**Comment by dzavalishin** [comment]
does not repeat, assume it to be fixed
