### ISSUE TITLE
reconnected vm win after restart does not get focus

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#164]
```
Need recreate owner tid and corresponding wtty code.
```

Original issue reported on code.google.com by `dmitry.zavalishin@gmail.com` on 20 Jun 2012 at 1:28

**Comment by dzavalishin** [comment]
Window owner field is keepint tid_t. Need one more `pvm_object_t vm_thread` field to reconnect to object land?
