### ISSUE TITLE
Console and Stats window positions aren't restored from snapshot

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#169]
```
What steps will reproduce the problem?
1. Try moving windows before snap is taken
2. Wait for snap to finish
3. Start from snap

```

Original issue reported on code.google.com by `seva.glu...@gmail.com` on 13 Aug 2012 at 11:51

**Comment by dzavalishin** [comment]
These are kernel windows, recreated on each reboot.
Possibly can be achieved with #179, but currently is not a bug.
