### ISSUE TITLE
USB drivers do not work

### ISSUE THREAD

**Issue by dzavalishin** [dzavalishin/phantomuserland#266]

**Comment by dzavalishin** [comment]
@my2coins need details, please attach logs here

**Comment by my2coins** [comment]
Here is how it is going on my laptop:
...
mmouse/ps2ms_do_init: PS/2 mouse reset
mmouse/ps2ms_purge_buffer: purge 0xFA
mmouse/ps2ms_purge_buffer: purge 0xAA
mmouse/ps2ms_purge_buffer: purge 0x 0
mmouse/ps2ms_do_init: PS/2 mouse set sample rate
mouse/ps2ms_purge_buffer: purge 0xFA
mouse/ps2ms_purge_buffer: purge 0xFA
mouse/ps2ms_purge_buffer: purge 0xFA
mouse/ps2ms_purge_buffer: purge 0xFA
mouse/ps2ms_purge_buffer: purge 0xFA
mouse/ps2ms_do_init: PS/2 mouse ask ID
mmouse/ps2ms_do_init: PS/2 mouse ID=0x 0
mouse/ps2ms_int_handler: FA
driver/probe_isa: Driver 'PS2 Mouse' attached to ISA @ 0xFFFFFFFF, IRQ 12
...
usb/usb_setup: init usb
uhci/uhci_init: UHCI init on dev 00:01.2 (io=c740)
boot/main: Sleep before tests to settle down boot activities
Usermode test suite runs with pid 10 tid 22
Phantom usermode test suite
-----
gettid = 22
getpid = 10
getuid = 0
getuid32 = 0
getpgrp = 10
getppid = 10
getegid = 0
uhci/configure_uhci: framelist 0x1c0d000
uhci/check_uhci_ports: Look for UHCI ports
usb/usb_enumerate: hub 0x41bdff24
usb/usb_enumerate: Look at port 0
getegid32 = 0
usb/usb_set_address: cntl 0x73cd00
uhci/uhci_alloc_control_pipe: uhci_alloc_control_pipe usb 0x73cd00
uhci/uhci_alloc_control_pipe: uhci_alloc_control_pipe pipe 0x6cc640
usb/send_default_control: pipe 0x6cc64c datasize 0
uhci/uhci_control: uhci_control 0x6cc64c
uhci/uhci_control: count = 2, datasize = 0, maxpacket = 8
uhci/uhci_dump: iobase c740, membase 1c0d000, frame 98, SOF 64
uhci/uhci_dump: cmd c1<Run,Conf,MaxPkt64>
uhci/uhci_dump: sts 2<IntrErr>
uhci/uhci_dump: irq 0
uhci/uhci_dump: td 73cfb0 link 6cc642 elem 1
uhci/uhci_dump: td 6cc640 link 73cfd2 elem 6cc6a4
uhci/uhci_dump: td 73cfd0 link 1 elem 73cf90
geteuid = 0
geteuid32 = 0
getgid = 0
getgid32 = 0
syscall/do_syscall_sw: Unimplemented syscall 36 called
getpgid = 0
USERMODE TEST PASSED: getters
...
KERNEL TEST PASSED: sem
Testing semaphores
sema wait 1
usb/check_tsc: timed out
uhci/wait_qh: timeout
uhci/wait_qh: Timeout on wait_qh 0x6cc640 (td=0x6cc6a0 s=400000 c=c1/2)
uhci/uhci_dump: iobase c740, membase 1c0d000, frame 1074, SOF 64
uhci/uhci_dump: cmd c1<Run,Conf,MaxPkt64>
uhci/uhci_dump: sts 2<IntrErr>
uhci/uhci_dump: irq 0
uhci/uhci_dump: td 73cfb0 link 6cc642 elem 1
uhci/uhci_dump: td 6cc640 link 73cfd2 elem 6cc6a4
uhci/uhci_dump: td 73cfd0 link 1 elem 73cf90
uhci/uhci_waittick: enter
uhci/uhci_dump: iobase c740, membase 1c0d000, frame 1154, SOF 64
uhci/uhci_dump: cmd c1<Run,Conf,MaxPkt64>
uhci/uhci_dump: sts 2<IntrErr>
uhci/uhci_dump: irq 0
uhci/uhci_dump: td 73cfb0 link 6cc642 elem 1
uhci/uhci_dump: td 6cc640 link 73cfd2 elem 1
uhci/uhci_dump: td 73cfd0 link 1 elem 73cf90
sema release 1 (direct)
uhci/uhci_waittick: leave ok
usb/usb_set_address: send def control failed at port 0
usb/usb_init_hub_port: Set address failed at port 0
usb/usb_enumerate: Look at port 1
usb/usb_init_hub_port: No dev at port 1
uhci/uhci_free_pipe: uhci_free_pipe 0x6cc64c
uhci/uhci_waittick: enter
uhci/uhci_dump: iobase c740, membase 1c0d000, frame 1318, SOF 64
uhci/uhci_dump: cmd c1<Run,Conf,MaxPkt64>
uhci/uhci_dump: sts 2<IntrErr>
uhci/uhci_dump: irq 0
uhci/uhci_dump: td 73cfb0 link 73cfd2 elem 1
uhci/uhci_dump: td 73cfd0 link 1 elem 73cf90
uhci/uhci_waittick: leave ok
sema wait 2
sema release 2 (softirq 0)
sema timeout
Done testing semaphores
KERNEL TEST PASSED: sem

In CI, I tried to output serial0.log to console, with no much success, though:
https://snap-ci.com/dzavalishin/phantomuserland/branch/master/logs/defaultPipeline/123/RegressionTest?back_to=build_history

**Comment by dzavalishin** [comment]
```
[32musb/usb_setup: init usb[0m
[32mohci/ohci_init: OHCI init on dev 00:05.0 (regs=0x41b00000)[0m
[33mide/setup_simple_ide: Found PCI IDE, BM base reg=0xC000, irq -1[0m
[32mohci/configure_ohci: config OHCI 0x7379c0[0m
[32mohci/start_ohci: ctl 0x7379c0[0m
[33mide/setup_simple_ide: Found 2 devices, dev 0 is ATA, dev 1 is ATA.[0m
Disk type ata size 504 Mb, sect 512 b, multisect 16
 * Has: 7b<LBA28,LBA48,DMA,Smart,Multisector,Flush>
 * Model 'QEMU HARDDISK                           '
 * Serial 'QM00001             '
Disk type ata size 500 Mb, sect 512 b, multisect 16
 * Has: 7b<LBA28,LBA48,DMA,Smart,Multisector,Flush>
 * Model 'QEMU HARDDISK                           '
 * Serial 'QM00002             '
Disk Partition /Ide0 (), 504 Mb, flags 40<IsDisk>
[32mohci/start_ohci: done, cntl 0x7379c0[0m
[32mohci/check_ohci_ports: 0x7379c0[0m
[32mohci/check_ohci_ports: will enumerate, ctl 0x7379c0[0m
[32musb/usb_enumerate: hub 0x41b3ff30[0m
[32musb/usb_enumerate: Look at port 0[0m
[32mohci/ohci_hub_detect: have dev on hub port 0[0m
[32musb/usb_set_address: cntl 0x7379c0[0m
[32mohci/ohci_alloc_control_pipe: ohci_alloc_control_pipe 0x7379c0[0m
[32musb/send_default_control: pipe 0x6e7650 datasize 0[0m
[32mohci/ohci_control: ohci_control pipe 0x6e7650[0m
[33mohci/dump_ohci_ed: OHCI ed hwInfo 80000 tail=0x6e76a0 head=0x6e7680 nextEd=0[0m
[32mohci/ohci_control: will wait_ed, pipe 6e7640, &ed = 6e7640[0m
[31mohci/ohci_control: wait_ed = 0[0m
[33mohci/dump_ohci_ed: OHCI ed hwInfo 80000 tail=0x6e76a0 head=0x6e76a1 nextEd=0[0m
[32mohci/ohci_alloc_control_pipe: ohci_alloc_control_pipe 0x7379c0[0m
[32musb/configure_usb_device: config_usb: 0x6e7690[0m
[32musb/get_device_info8: enter[0m
[32musb/send_default_control: pipe 0x6e7690 datasize 8[0m
[32mohci/ohci_control: ohci_control pipe 0x6e7690[0m
[33mohci/dump_ohci_ed: OHCI ed hwInfo 80001 tail=0x6e76f0 head=0x6e76c0 nextEd=0x6e7640[0m
[32mohci/ohci_control: will wait_ed, pipe 6e7680, &ed = 6e7680[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[32mohci/wait_ed: again[0m
[31musb/check_tsc: timed out[0m
[31mohci/wait_ed: timeout[0m
[31mohci/ohci_control: wait_ed = -1[0m
[33mohci/dump_ohci_ed: OHCI ed hwInfo 80001 tail=0x6e76f0 head=0x6e76c0 nextEd=0x6e7640[0m
[31musb/configure_usb_device: get_device_info8 rc = -1[0m
[32mohci/ohci_free_pipe: ohci_free_pipe 0x6e7690[0m
[32musb/usb_enumerate: Look at port 1[0m
[31musb/usb_init_hub_port: No dev at port 1[0m
[32musb/usb_enumerate: Look at port 2[0m
[31musb/usb_init_hub_port: No dev at port 2[0m
[32mohci/ohci_free_pipe: ohci_free_pipe 0x6e7650[0m
```
