### ISSUE TITLE
board_panic_wait_keypress doesn't wait for keypress

### ISSUE THREAD

**Issue by my2coins** [dzavalishin/phantomuserland#303]
It's not possible to connect gdb because of this issue.

**Comment by dzavalishin** [comment]
keyboard.c 

int phantom_scan_console_getc(void)
{
    do {
        while((inb(0x64) & K_OBUF_FUL) == 0)
            ;
    } while( inb(0x60) & 0x80 );
    return 0;
}

**Comment by my2coins** [comment]
Works in snap mode, doesn't work in test mode (still doesn't wait for keypress) -- different processing?

**Comment by dzavalishin** [comment]
kernel=(hd0,0)/boot/phantom -d=10 -unattended -- 

-unattended turns it off - can it be a reason?

**Comment by my2coins** [comment]
Of course tried w/o -unattended :) Seems to be fixed now, though

**Comment by my2coins** [comment]
Spinlock reenter panic caught in [build #140](https://snap-ci.com/dzavalishin/phantomuserland/branch/master/logs/defaultPipeline/140/RegressionTest?back_to=build_history), and gdb didn't run

**Comment by dzavalishin** [comment]
да, спорадически при старте что-то крешится. :(


On Wed, Mar 16, 2016 at 5:30 PM, Seva Gluschenko <notifications@github.com>
wrote:

> Spinlock reenter panic caught in build #140
> <https://snap-ci.com/dzavalishin/phantomuserland/branch/master/logs/defaultPipeline/140/RegressionTest?back_to=build_history>,
> and gdb didn't run
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/dzavalishin/phantomuserland/issues/303#issuecomment-197354909>
>



-- 

Dmitriy Zavalishin, Owner, +7 916 690 3208, dz@dz.ru
DZ Systems: Digital Zone & E-Legion, http://dz.ru & http://e-legion.com

**Comment by dzavalishin** [comment]
Dup #323

**Comment by my2coins** [comment]
Here we go again. Missed several chances to backtrace panics.

**Comment by dzavalishin** [comment]
так что - не ждёт?
