### ISSUE TITLE
class import fails in ru.dz.demo.weather.ph (make -C pib is broken)

### ISSUE THREAD

**Issue by my2coins** [dzavalishin/phantomuserland#315]
:-- ru.dz.demo.chart.pc
src/ru.dz/ru.dz.demo.chart.ph:15: error: Can't import .internal.io.tty
src/ru.dz/ru.dz.demo.chart.ph:16: error: Can't import .internal.window
src/ru.dz/ru.dz.demo.chart.ph:17: error: Can't import .internal.connection
src/ru.dz/ru.dz.demo.chart.ph:18: error: Can't import .ru.dz.phantom.system.runnable
src/ru.dz/ru.dz.demo.chart.ph:33: error: Class .internal.window is not defined - forgot to import?
src/ru.dz/ru.dz.demo.chart.ph:34: error: Class .internal.connection is not defined - forgot to import?
src/ru.dz/ru.dz.demo.chart.ph:45: error: Class .internal.window is not defined - forgot to import?
src/ru.dz/ru.dz.demo.chart.ph:61: error: Class .internal.connection is not defined - forgot to import?
Compile failed: don't know class in MethodNode get return type (setWinPosition)
make[1]: *** [ru.dz.demo.chart.pc] Error 1

**Comment by dzavalishin** [comment]
@my2coins Must be gone now?

**Comment by my2coins** [comment]
@dzavalishin still there

**Comment by my2coins** [comment]
BTW it's in snap-ci now:

https://snap-ci.com/dzavalishin/phantomuserland/branch/master/logs/defaultPipeline/127/RegressionTest?back_to=build_history

**Comment by dzavalishin** [comment]
got it. dependencies, build order.

**Comment by my2coins** [comment]
It's okay now

**Comment by my2coins** [comment]
It's okay now

**Comment by dzavalishin** [comment]
not completely, one more fix

**Comment by my2coins** [comment]
--- make classes bulk ---
...
java.io.FileNotFoundException: phantom.environment.pc (No such file or directory)

**Comment by dzavalishin** [comment]
pls add corresponding dependency to sys/Makefile

**Comment by dzavalishin** [comment]
Not a dependency, some makefile error. :( If it builds .pc files, clause

```
$(TARGET): $(filter-out $(EXCLUDED_PCFILES), $(PCFILES) )
	@echo --- make classes bulk ---
	$(MKBULK) $(TARGET) $(filter-out $(OFF) ,$^)
```

passes one file to mkbulk without path name. :(

Don't know why.

**Comment by dzavalishin** [comment]
Now this one duplicates #309

**Comment by dzavalishin** [comment]
btw running make twice fixes it :)

On Sun, Mar 13, 2016 at 10:33 PM, Seva Gluschenko <notifications@github.com>
wrote:

> --- make classes bulk ---
> ...
> java.io.FileNotFoundException: phantom.environment.pc (No such file or
> directory)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dzavalishin/phantomuserland/issues/315#issuecomment-196028782>
> .
>



-- 

Dmitriy Zavalishin, Owner, +7 916 690 3208, dz@dz.ru
DZ Systems: Digital Zone & E-Legion, http://dz.ru & http://e-legion.com
