### ISSUE TITLE
pool test failed

### ISSUE THREAD

**Issue by dzavalishin** [dzavalishin/phantomuserland#319]
test.pool/_show_free: 512 free, 0 used in pool
test.pool/do_test_pool: check make/kill
Test fail: 2 == pool_get_used( pool ) is not true at 151
!!! KERNEL TEST FAILED: pool -> -1 (Unknown error: -1)

**Comment by dzavalishin** [comment]
Does not repeat. Sync?

**Comment by dzavalishin** [comment]
Does repeat, fixed in c7fff9a

**Comment by dzavalishin** [comment]
(Was error in test code, not pool code)

**Comment by my2coins** [comment]
Looks like now test hang in threads
