### ISSUE TITLE
QEMU for linux not found in qemu/0.14.1 folder

### ISSUE THREAD

**Issue by samuelsh** [dzavalishin/phantomuserland#329]
run]# echo $PHANTOM_HOME
/qa/phantomuserland

run]# bash -x ./phantom_clean.sh
\+ ./zero_ph_img.sh
500+0 records in
500+0 records out
524288000 bytes (524 MB) copied, 0.893248 s, 587 MB/s
1+0 records in
1+0 records out
4096 bytes (4.1 kB) copied, 1.5558e-05 s, 263 MB/s
1024+0 records in
1024+0 records out
4194304 bytes (4.2 MB) copied, 0.0522744 s, 80.2 MB/s
\+ ./phantom.sh
rm: cannot remove `serial0.log.old1': No such file or directory
mv: cannot stat `serial0.log.old': No such file or directory
mv: cannot stat `serial0.log': No such file or directory
Run qemu/0.14.1/qemu
./phantom.sh: line 42: qemu/0.14.1/qemu: No such file or directory

*** Indeed there's no quemu for Linux :(
run]# ls -latrh qemu/0.14.1
total 48M
-rw-r--r-- 1 root root 317K Mar 17 15:29 SDL.dll
drwxr-xr-x 2 root root 4.0K Mar 17 15:29 bios
drwxr-xr-x 2 root root 4.0K Mar 17 15:29 keymaps
-rw-r--r-- 1 root root  71K Mar 17 15:29 libz-1.dll
-rw-r--r-- 1 root root 341K Mar 17 15:29 qemu-img.exe
-rw-r--r-- 1 root root 354K Mar 17 15:29 qemu-io.exe
-rw-r--r-- 1 root root 2.8M Mar 17 15:29 qemu-system-arm.exe
-rw-r--r-- 1 root root 1.5M Mar 17 15:29 qemu-system-cris.exe
-rw-r--r-- 1 root root 1.9M Mar 17 15:29 qemu-system-m68k.exe
-rw-r--r-- 1 root root 1.5M Mar 17 15:29 qemu-system-microblaze.exe
-rw-r--r-- 1 root root 2.9M Mar 17 15:29 qemu-system-mips.exe
-rw-r--r-- 1 root root 3.1M Mar 17 15:29 qemu-system-mips64.exe
-rw-r--r-- 1 root root 3.1M Mar 17 15:29 qemu-system-mips64el.exe
-rw-r--r-- 1 root root 2.9M Mar 17 15:29 qemu-system-mipsel.exe
-rw-r--r-- 1 root root 3.2M Mar 17 15:29 qemu-system-ppc.exe
-rw-r--r-- 1 root root 3.9M Mar 17 15:29 qemu-system-ppc64.exe
-rw-r--r-- 1 root root 3.2M Mar 17 15:29 qemu-system-ppcemb.exe
-rw-r--r-- 1 root root 1.9M Mar 17 15:29 qemu-system-sh4.exe
-rw-r--r-- 1 root root 1.9M Mar 17 15:29 qemu-system-sh4eb.exe
-rw-r--r-- 1 root root 1.7M Mar 17 15:29 qemu-system-sparc.exe
-rw-r--r-- 1 root root 2.6M Mar 17 15:29 qemu-system-sparc64.exe
-rw-r--r-- 1 root root 2.8M Mar 17 15:29 qemu-system-x86_32.exe
-rw-r--r-- 1 root root 3.3M Mar 17 15:29 qemu-system-x86_64.exe
-rw-r--r-- 1 root root 3.3M Mar 17 15:29 qemu.exe

**Comment by my2coins** [comment]
try autotest.sh, it's written for Linux

**Comment by samuelsh** [comment]
Tried under debian jessie but still not working.
autotest.sh calls finally phantom.sh so I'm running into the same issue. 
Looks like there's no qemu for Linux in that folder.
I you would like I can try to fix it.

**Comment by my2coins** [comment]
You surprise me alot :) I wrote autotest.sh, and I may assure you that it does NOT call phantom.sh (and grep agrees :).

**Comment by samuelsh** [comment]
Yup, confused with .phantom_clean.sh. sorry :)

**Comment by dzavalishin** [comment]
I think we should provide a 0.15.1 binary for linex, nevertheless.
We'll need one for Innolpolis lecture too.

**Comment by my2coins** [comment]
Unless statically linked, it will be at high risk of numerous incompatibilities in shared libs. I'd rather requested QEMU installation as a pre-requisite or access for building QEMU on target in advance.

Would it be even better to try and run on physical hardware there?

**Comment by dzavalishin** [comment]
Physical hw is unreal, too hard to prepare, we'll have 1.5 hours for all...

On Tue, Mar 22, 2016 at 6:59 PM, Seva Gluschenko <notifications@github.com>
wrote:

> Unless statically linked, it will be at high risk of numerous
> incompatibilities in shared libs. I'd rather requested QEMU installation as
> a pre-requisite or access for building QEMU on target in advance.
>
> Would it be even better to try and run on physical hardware there?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/dzavalishin/phantomuserland/issues/329#issuecomment-199880358>
>



-- 

Dmitriy Zavalishin, Owner, +7 916 690 3208, dz@dz.ru
DZ Systems: Digital Zone & E-Legion, http://dz.ru & http://e-legion.com

**Comment by dzavalishin** [comment]
Have QEMU Linux package in /etc
