### ISSUE TITLE
Phantom OS panic and reboot due to assertion '!hal_mutex_is_locked(&i->lock)'

### ISSUE THREAD

**Issue by samuelsh** [dzavalishin/phantomuserland#330]
Running under Cygwin on Win7 x64

<0>Mar 17 14:02:53 snap: started
ipv4 packet for someone else: 192.168.1.100
.internal.connection: Connect to 'tmr:'
Init timer<0>Mar 17 14:02:55 snap: wait 4 pgout to settle
<0>Mar 17 14:02:55 snap: stop world
ipv4 packet for someone else: 192.168.1.100
ipv4 packet for someone else: 192.168.1.100
ERR: File not found for class 'ru.dz.phantom.system.shell_callback'
Class is: .ru.dz.phantom.system.shell_callback<0>Mar 17 14:03:14 snap: threads stopped
<0>Mar 17 14:03:14 snap: hold still, say 'cheese!'...
Panic: vm_map.c:1157, vm_map_do_for_all: assertion '!hal_mutex_is_locked(&i->lock)' failed

**Comment by dzavalishin** [comment]
Thanx. Repeats steadily? Can you catch it with gdb? Any stack trace in log file?

**Comment by samuelsh** [comment]
Yep it's pretty repoduceable
Didn't find stack trace in log 
Could be coredump somewhere?
Anyway will try to repro with gdb.

Thanks 
Sam

**Comment by samuelsh** [comment]
Got some additional info with GDB :)

> Breakpoint 1, panic (fmt=0x620f88 "vm_map.c:%u, %s: assertion '!hal_mutex_is_locked(&i->lock)' failed") at t_panic.c:31
> 31          if(panic_reenter)
> (gdb) bt
> #0  panic (fmt=0x620f88 "vm_map.c:%u, %s: assertion '!hal_mutex_is_locked(&i->lock)' failed") at t_panic.c:31
> #1  0x001730f1 in vm_map_do_for_all (func=0x17318e <mark_for_snap>, lock=0) at vm_map.c:1157
> #2  0x0017318c in vm_map_for_all_locked (func=0x17318e <mark_for_snap>) at vm_map.c:1175
> #3  0x001736c0 in do_snapshot () at vm_map.c:1396
> #4  0x00173c0d in vm_map_snapshot_thread () at vm_map.c:1636
> #5  0x001a40d4 in kernel_thread_starter (func=0x173b89 <vm_map_snapshot_thread>) at t_create.c:127
> #6  0x001a4705 in phantom_thread_c_starter () at t_create.c:420
> #7  0x001a7398 in _phantom_thread_trampoline () at /home/samuels/projects/phantomuserland/phantom/threads/ia32/thread.S:99
> (gdb) bt full
> #0  panic (fmt=0x620f88 "vm_map.c:%u, %s: assertion '!hal_mutex_is_locked(&i->lock)' failed") at t_panic.c:31
>         ap = 0x1a5097 <hal_mutex_unlock+218> "\270"
> #1  0x001730f1 in vm_map_do_for_all (func=0x17318e <mark_for_snap>, lock=0) at vm_map.c:1157
>         total = 8193
>         i = 0x1cee390
>         __func__ = "vm_map_do_for_all"
> #2  0x0017318c in vm_map_for_all_locked (func=0x17318e <mark_for_snap>) at vm_map.c:1175
> No locals.
> #3  0x001736c0 in do_snapshot () at vm_map.c:1396
>         enabled = 512
>         prio = 7
>         new_snap_head = 0
>         toFree = 512
>         actual1 = 0
>         actual2 = 0
> #4  0x00173c0d in vm_map_snapshot_thread () at vm_map.c:1636
>         i = -1
> #5  0x001a40d4 in kernel_thread_starter (func=0x173b89 <vm_map_snapshot_thread>) at t_create.c:127
>         thread = 0x173b89 <vm_map_snapshot_thread>
> #6  0x001a4705 in phantom_thread_c_starter () at t_create.c:420
>         func = 0x1a40c3 <kernel_thread_starter>
>         arg = 0x173b89 <vm_map_snapshot_thread>
>         t = 0x1f56400
> #7  0x001a7398 in _phantom_thread_trampoline () at /home/samuels/projects/phantomuserland/phantom/threads/ia32/thread.S:99
> No locals.
> (gdb)
