### ISSUE TITLE
gdb and unattended boot mode

### ISSUE THREAD

**Issue by samuelsh** [dzavalishin/phantomuserland#337]
OS: CentOS 6

less -r run/test/serial0.log

spinlock reenter detected, prev enter was here:
Stack:-   6ae260: ?
Panic: reenter

*** Looks like when GDB started process is already dead/
Any suggestions how to catch it?

**Comment by my2coins** [comment]
This happens because Phantom does not wait for keypress in unattended mode. We need to change this somehow.

**Comment by dzavalishin** [comment]
just remove -unattended key from run/fat/boot/menu.lst:

kernel=(hd0,0)/boot/phantom -d=10 -unattended --

**Comment by dzavalishin** [comment]
should we remove it from repository file too, btw?

**Comment by my2coins** [comment]
In the test scripts, it's generated on the fly (i.e., literally, not needed). In fact, I have already changed defaults there, so that one needs to specify -unattended explicitly in the command line to have it included.

**Comment by dzavalishin** [comment]
dup of #323?

**Comment by my2coins** [comment]
No, it is about catching a panic with gdb. Currently the only solution is to run interactively (i.e. not -unattended), although I'm looking into possibilities to proceed it in the CI mode.

**Comment by my2coins** [comment]
Scripts are now changed, so that gdb starts in advance and collects backtrace wherever panic occurs and regardless unattended mode
