### ISSUE TITLE
connect url http://smart.:8080/rest/items/Current_Outdoor_Air_Temp/state

### ISSUE THREAD

**Issue by my2coins** [dzavalishin/phantomuserland#343]
The URL is local to some setup, so it can't be reached from everywhere. Need to change to something universal.

**Comment by dzavalishin** [comment]
Any idea? Need some data source for diagram, such as current temperature somewhere. Mabe Yandex has some public Yandex.Weather API where we can get current temperature @ north pole or some other pretty place?

**Comment by dzavalishin** [comment]
https://export.yandex.ru/weather-ng/forecasts/27612.xml for Moscow, but need XML parser...

**Comment by dzavalishin** [comment]
list: http://michaelwelburn.com/2011/11/02/comparing-weather-apis/
