### ISSUE TITLE
Need hashmap class w complete access from C

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#36]
```
for things like maps of settings, etc

```

Original issue reported on code.google.com by `dmitry.zavalishin@gmail.com` on 4 Jun 2010 at 9:26

**Comment by dzavalishin** [comment]
Possible code:
 * https://github.com/petewarden/c_hashmap/blob/master/hashmap.c
 * https://github.com/petewarden/c_hashmap/blob/master/hashmap.h
 * https://github.com/petewarden/c_hashmap/blob/master/main.c

**Comment by dzavalishin** [comment]
one more: http://www2.informatik.hu-berlin.de/~weber/slipOff/hashmap_c.html

**Comment by dzavalishin** [comment]
http://elliottback.com/wp/hashmap-implementation-in-c/
http://stackoverflow.com/questions/838404/implementing-a-hashmap

**Comment by dzavalishin** [comment]
http://c.learncodethehardway.org/book/ex37.html

**Comment by dzavalishin** [comment]
Mostly written for .internal.directory, need tests. Some tests written too.
Need deletion and test for it.

**Comment by dzavalishin** [comment]
Have deletion. Need from-kernel interface. vm_connect.c?

**Comment by dzavalishin** [comment]
Tested and seem to be ok
