### ISSUE TITLE
pvm_exec_panic: stack underflow

### ISSUE THREAD

**Issue by my2coins** [dzavalishin/phantomuserland#372]
Caught in snap-ci, first reproducible after https://github.com/dzavalishin/phantomuserland/commit/de4821d3e9ea6223eac05d012a4b928e581b5141

The console log can be found here:

https://app.snap-ci.com/dzavalishin/phantomuserland/branch/master/logs/defaultPipeline/282/SnapTest

**Comment by dzavalishin** [comment]
don't know how to reproduce, didn't happen again...
