### ISSUE TITLE
error: no suitable video mode found [Real Hardware, Intel Graphics]

### ISSUE THREAD

**Issue by SuperPrower** [dzavalishin/phantomuserland#408]
При запуске с grub2 на настоящем железе появляется такая ошибка
Без понятия, как это дебажить, так что просто оставлю это тут

![photo_2017-05-31_14-59-40](https://cloud.githubusercontent.com/assets/10908110/26631011/d763ed00-4611-11e7-86e2-297b0a506591.jpg)

**Comment by dzavalishin** [comment]
а это не фантомовское сообщение, вроде. я не нашёл такого в коде.

**Comment by dzavalishin** [comment]
Вообще для отладки на живом железе нужен GDB stub в ядре. Давно хотел это сделать...

**Comment by SuperPrower** [comment]
Действительно не фантомовское. Что-то нашёл по этому поводу на Arch Wiki, буду дорабатывать конфигурацию.
