### ISSUE TITLE
Assignment to typeless variables is not working

### ISSUE THREAD

**Issue by PolarNorth** [dzavalishin/phantomuserland#467]
Assignments to typeless variables cause compilation error `Compile failed: ru.dz.plc.util.PlcException: unknown type of unknown`, however assignment from them works. Also it is not possible to declare such variables inside methods for now, only as fields.

**Comment by dzavalishin** [comment]
It is ok to assign reference (object) type, but not numeric. For numeric compiler must know type of var. As long as we have no type infer it is ok. 

Looking for this case found bug in numeric var definition code. :)
