### ISSUE TITLE
j2ptranslator: object fields access

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#84]
```
Direct access to object field failure

```

Original issue reported on code.google.com by `akhtyamo...@gmail.com` on 15 Jan 2011 at 2:22

**Comment by dzavalishin** [comment]
Basically fixed by generating getter/setter. Field access with getter/setter is implemented also. Untested/

**Comment by dzavalishin** [comment]
Code with getter worked.
