### ISSUE TITLE
test wins daemon

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#96]
```
is only possible on real hw? or tap?

```

Original issue reported on code.google.com by `dmitry.zavalishin@gmail.com` on 27 Feb 2011 at 5:39

**Comment by dzavalishin** [comment]
Phantom contains wins daemon in phantom/apps/winsd, need some way to tell if it works.

**Comment by dzavalishin** [comment]
depends on #433

**Comment by dzavalishin** [comment]
Unsure if we need it at all

**Comment by dzavalishin** [comment]
Comes to #542
